### PR TITLE
Upgrade plugin to be compatible with strapi V5

### PR DESCRIPTION
**Pull request by jhoward1994**
Hi @nshenderov 

Thanks for your great plugin!

As you might be aware Strapi V5 will be released soon. Internally we have been working on the v4-v5 plugin migration process and selected this plugin based on it's prominence on the marketplace to migrate internally.

This PR is a result of that process. We would very much appreciate your feedback, hopefully we can get this merged soon so Strapi V5 users can continue enjoying your plugin.

I'm happy to discuss anything you like in this PR. You will see the main changes are:

- Restructuring of the codebase
- Build process using `strapi-plugin`
- Upgraded @strapi/design-system - see https://design-system-git-main-strapijs.vercel.app/?path=/docs/getting-started-migration-guides-v1-to-v2--docs
- Deprecated `@strapi/helper-plugin` - see https://docs-next.strapi.io/dev-docs/migration/v4-to-v5/additional-resources/helper-plugin for an overview of the process follwed here
- Major version upgrade of plugin

Thanks 🙂

### CODE REVIEW

**Comment by nshenderov** [comment]
@jhoward1994

Wow, thank you for your PR! I didn't expect someone would help with the migration to v5.

I'm currently finishing up a new major release for Strapi v4 that I've been working on in my spare time. It includes significant codebase refactoring and introduces some breaking changes that will affect the plugin's configuration. I expect to complete and release it in a few days. After that, I plan to start working on the migration to v5.

It would be great if you could update this PR with the changes that will be part of v3.0 of the plugin.

**Comment by BlackWatch021** [comment]
Hey @nshenderov , hope you are doing great. I know this isn't the write place to ask this. But I need your help. So, is there any place where I can connect with you or is it fine if I post my question here only?

**Comment by nshenderov** [comment]
@BlackWatch021 
You can post your question as an issue or in the discussion section (but please check previous issues first), or you can ask the community in the Strapi Discord

**Comment by BlackWatch021** [comment]
@nshenderov thanks, I forgot about the issue section. Let me go through them.

**Comment by hanpaine** [comment]
Hey @nshenderov - happy Wednesday! We definitely missed a trick in not letting you know we would trial the v5 migration on your CKEditor plugin in advance. Apologies for that, it would have been much easier to manage timings around concurrent changes you're making to the plugin - definitely a lesson learned for us there. We've moved onto the next migrations now I'm afraid and are also very, very close to Stable launch, so don't have capacity to come back and rework this PR for further changes unfortunately. When your plugin changes are completed and you have a chance look at and update this PR, if you have any questions, I'm sure we can help though. Thanks again for an awesome plugin!

**Comment by nshenderov** [comment]
Thanks again for your help. I’ve decided to start fresh with the new version instead of updating this PR.

**Pull request closed without merging**
